// Types for static image imports (`import shot from '@/public/screenshots/x.png'`). next-env.d.ts
// provides them too, but it's generated by `next build`/`next dev` and git-ignored, so a plain
// `tsc --noEmit` (CI's first step) wouldn't see them.
/// <reference types="next/image-types/global" />
